project:
  type: website
  output-dir: docs
website:
  title: "Tianhao Cao"  # Name
  favicon: favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/SNALYF
      - icon: linkedin
        href: https://www.linkedin.com/in/tianhao-cao-mds/
      - icon: envelope
        href: mailto:snalyf.c@gmail.com

format:
  html:
    theme: darkly
    css: styles.css
    toc: true 
    include-in-header:
      - scripts/fx.html
    include-after-body: scripts/translate.html